### ISSUE TITLE
Compilation Error in accel-sim.out (main.cc and trace_driven.cc)

### ISSUE THREAD

**Issue by Sikiruu** [accel-sim/accel-sim-framework#354]
The issue occurs in the gpu-simulator component, specifically in `main.cc` and `trace_driven.cc`. Despite ensuring that the environment is set up correctly and that all required directories (bin/release, build/release) exist, the errors persist.

Here is the relevant error log:

```plaintext
In file included from /root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/../src/cuda-sim/../gpgpu-sim/shader.h:54,
                 from /root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/../src/cuda-sim/cuda-sim.h:37,
                 from /root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/gpgpu_context.h:3,
                 from main.cc:13:
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/../src/cuda-sim/../gpgpu-sim/gpu-cache.h: In constructor 'baseline_cache::baseline_cache(const char*, cache_config&, int, int, mem_fetch_interface*, mem_fetch_status, cache_gpu_level, gpgpu_sim*)':
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/../src/cuda-sim/../gpgpu-sim/gpu-cache.h:1479:24: warning: 'baseline_cache::m_bandwidth_management' will be initialized after [-Wreorder]
 1479 |   bandwidth_management m_bandwidth_management;
      |                        ^~~~~~~~~~~~~~~~~~~~~~
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/../src/cuda-sim/../gpgpu-sim/gpu-cache.h:1399:19: warning:   'cache_gpu_level baseline_cache::m_level' [-Wreorder]
 1399 |   cache_gpu_level m_level;
      |                   ^~~~~~~
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/../src/cuda-sim/../gpgpu-sim/gpu-cache.h:1282:3: warning:   when initialized here [-Wreorder]
 1282 |   baseline_cache(const char *name, cache_config &config, int core_id,
      |   ^~~~~~~~~~~~~~
In file included from ../gpgpu-sim/shader.h:54,
                 from cuda-sim.h:37,
                 from cuda-sim.cc:33:
../gpgpu-sim/gpu-cache.h: In constructor 'baseline_cache::baseline_cache(const char*, cache_config&, int, int, mem_fetch_interface*, mem_fetch_status, cache_gpu_level, gpgpu_sim*)':
../gpgpu-sim/gpu-cache.h:1479:24: warning: 'baseline_cache::m_bandwidth_management' will be initialized after [-Wreorder]
 1479 |   bandwidth_management m_bandwidth_management;
      |                        ^~~~~~~~~~~~~~~~~~~~~~
../gpgpu-sim/gpu-cache.h:1399:19: warning:   'cache_gpu_level baseline_cache::m_level' [-Wreorder]
 1399 |   cache_gpu_level m_level;
      |                   ^~~~~~~
../gpgpu-sim/gpu-cache.h:1282:3: warning:   when initialized here [-Wreorder]
 1282 |   baseline_cache(const char *name, cache_config &config, int core_id,
      |   ^~~~~~~~~~~~~~
main.cc: In function 'int main(int, const char**)':
main.cc:151:29: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<long unsigned int>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
  151 |           for (int l = 0; l < busy_streams.size(); l++) {
      |                           ~~^~~~~~~~~~~~~~~~~~~~~
main.cc:165:32: error: no matching function for call to 'gpgpu_sim::print_stats()'
  165 |       m_gpgpu_sim->print_stats();
      |                                ^
In file included from /root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/cuda_api_object.h:14,
                 from /root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/gpgpu_context.h:9,
                 from main.cc:13:
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/../src/gpgpu-sim/gpu-sim.h:592:8: note: candidate: 'void gpgpu_sim::print_stats(long long unsigned int)'
  592 |   void print_stats(unsigned long long streamID);
      |        ^~~~~~~~~~~
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/../src/gpgpu-sim/gpu-sim.h:592:8: note:   candidate expects 1 argument, 0 provided
In file included from /root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/cuda-sim/../gpgpu-sim/shader.h:54,
                 from /root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/cuda-sim/cuda-sim.h:37,
                 from trace_driven.cc:48:
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/cuda-sim/../gpgpu-sim/gpu-cache.h: In constructor 'baseline_cache::baseline_cache(const char*, cache_config&, int, int, mem_fetch_interface*, mem_fetch_status, cache_gpu_level, gpgpu_sim*)':
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/cuda-sim/../gpgpu-sim/gpu-cache.h:1479:24: warning: 'baseline_cache::m_bandwidth_management' will be initialized after [-Wreorder]
 1479 |   bandwidth_management m_bandwidth_management;
      |                        ^~~~~~~~~~~~~~~~~~~~~~
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/cuda-sim/../gpgpu-sim/gpu-cache.h:1399:19: warning:   'cache_gpu_level baseline_cache::m_level' [-Wreorder]
 1399 |   cache_gpu_level m_level;
      |                   ^~~~~~~
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/cuda-sim/../gpgpu-sim/gpu-cache.h:1282:3: warning:   when initialized here [-Wreorder]
 1282 |   baseline_cache(const char *name, cache_config &config, int core_id,
      |   ^~~~~~~~~~~~~~
make: *** [Makefile:66: build/release/main.o] Error 1
make: *** Waiting for unfinished jobs....
trace_driven.cc: In constructor 'trace_kernel_info_t::trace_kernel_info_t(dim3, dim3, trace_function_info*, trace_parser*, trace_config*, kernel_trace_t*)':
trace_driven.cc:94:55: error: no matching function for call to 'kernel_info_t::kernel_info_t(dim3&, dim3&, trace_function_info*&)'
   94 |     : kernel_info_t(gridDim, blockDim, m_function_info) {
      |                                                       ^
In file included from ../ISA_Def/ampere_opcode.h:9,
                 from trace_driven.cc:40:
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/abstract_hardware_model.h:325:3: note: candidate: 'kernel_info_t::kernel_info_t(const kernel_info_t&)'
  325 |   kernel_info_t(const kernel_info_t &);   // disable copy constructor
      |   ^~~~~~~~~~~~~
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/abstract_hardware_model.h:325:3: note:   candidate expects 1 argument, 3 provided
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/abstract_hardware_model.h:238:3: note: candidate: 'kernel_info_t::kernel_info_t(dim3, dim3, function_info*, std::map<std::__cxx11::basic_string<char>, const cudaArray*>, std::map<std::__cxx11::basic_string<char>, const textureInfo*>)'
  238 |   kernel_info_t(
      |   ^~~~~~~~~~~~~
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/abstract_hardware_model.h:238:3: note:   candidate expects 5 arguments, 3 provided
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/abstract_hardware_model.h:236:3: note: candidate: 'kernel_info_t::kernel_info_t(dim3, dim3, function_info*, long long unsigned int)'
  236 |   kernel_info_t(dim3 gridDim, dim3 blockDim, class function_info *entry,
      |   ^~~~~~~~~~~~~
/root/accel-sim-framework/gpu-simulator/gpgpu-sim/src/abstract_hardware_model.h:236:3: note:   candidate expects 4 arguments, 3 provided
trace_driven.cc: In member function 'bool trace_warp_inst_t::parse_from_trace_struct(const inst_trace_t&, const std::unordered_map<std::__cxx11::basic_string<char>, OpcodeChar>*, const trace_config*, const kernel_trace_t*)':
trace_driven.cc:199:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
  199 |     if(it2 != OpcPowerMap->end())
      |     ^~
trace_driven.cc:201:7: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  201 |       oprnd_type = get_oprnd_type(op, sp_op);
      |       ^~~~~~~~~~
make[1]: *** [Makefile:58: ../build/release/trace_driven.o] Error 1
make: *** [Makefile:77: trace-driven] Error 2
```

**Environment Details:**

- OS: Docker on Ubuntu 20.04
- Driver Version: 470
- CUDA Toolkit Version: 11.0.3

If any additional information is needed, please let me know. Thank you for your assistance!

**Comment by JRPan** [comment]
Release branch should work. Maybe you are mixing release accel-sim and dev gpgpu-sim?

I would suggest use dev anyway. But the latest dev gpgpu-sim is broken :)
Please try ` git checkout 667834cfe5214523edd7769aeab77f91b7137686` under **gpgpu-sim** folder. This is the lastest known working commit (just 1 behind head). We are working on a fix.

Let me know if dev works.

**Comment by ConvolutedDog** [comment]
To solve this, some changes need to be made across two repositories, but the Actions workflow only triggers updates for one repository at a time. So in this case, I don't know how to submit a PR and make the workflow pass. Below are the modifications made in each repository:

### Changes in gpgpu-sim_distribution:dev:
```diff
diff --git a/cuobjdump_to_ptxplus/ptx.y b/cuobjdump_to_ptxplus/ptx.y
index 45392fb9..929cae06 100644
--- a/cuobjdump_to_ptxplus/ptx.y
+++ b/cuobjdump_to_ptxplus/ptx.y
@@ -213,7 +213,7 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 %type <ptr_value> function_decl
 
 %{
-       #include "ptx_parser.h"
+       #include "../cuobjdump_to_ptxplus/ptx_parser.h"
        #include <stdlib.h>
        #include <string.h>
        #include <math.h>
diff --git a/src/cuda-sim/ptx.y b/src/cuda-sim/ptx.y
index 61183e88..77db7713 100644
--- a/src/cuda-sim/ptx.y
+++ b/src/cuda-sim/ptx.y
@@ -229,7 +229,7 @@ class ptx_recognizer;
 %type <ptr_value> function_decl
 
 %{
-       #include "ptx_parser.h"
+       #include "../cuda-sim/ptx_parser.h"
        #include <stdlib.h>
        #include <string.h>
        #include <math.h>
diff --git a/src/gpgpu-sim/gpu-sim.h b/src/gpgpu-sim/gpu-sim.h
index d0c2a176..a4d07d3e 100644
--- a/src/gpgpu-sim/gpu-sim.h
+++ b/src/gpgpu-sim/gpu-sim.h
@@ -78,6 +78,7 @@ extern tr1_hash_map<new_addr_type, unsigned> address_random_interleaving;
  * @return false
  */
 extern bool is_SST_buffer_full(unsigned core_id);
+__attribute__((weak)) bool is_SST_buffer_full(unsigned core_id) { return false; }
 
 /**
  * @brief Send loads to SST memory backend
@@ -89,6 +90,8 @@ extern bool is_SST_buffer_full(unsigned core_id);
  */
 extern void send_read_request_SST(unsigned core_id, uint64_t address,
                                   size_t size, void *mem_req);
+__attribute__((weak)) void send_read_request_SST(unsigned core_id, uint64_t address,
+                                   size_t size, void *mem_req) {}
 
 /**
  * @brief Send stores to SST memory backend
@@ -100,6 +103,8 @@ extern void send_read_request_SST(unsigned core_id, uint64_t address,
  */
 extern void send_write_request_SST(unsigned core_id, uint64_t address,
                                    size_t size, void *mem_req);
+__attribute__((weak)) void send_write_request_SST(unsigned core_id, uint64_t address,
+                                   size_t size, void *mem_req) {}
 
 enum dram_ctrl_t { DRAM_FIFO = 0, DRAM_FRFCFS = 1 };
 
diff --git a/src/gpgpusim_entrypoint.cc b/src/gpgpusim_entrypoint.cc
index 839fef61..e2b711ed 100644
--- a/src/gpgpusim_entrypoint.cc
+++ b/src/gpgpusim_entrypoint.cc
@@ -56,6 +56,7 @@ class stream_manager *g_stream_manager() {
 
 // SST callback
 extern void SST_callback_cudaThreadSynchronize_done();
+__attribute__((weak)) void SST_callback_cudaThreadSynchronize_done() {}
 
 void *gpgpu_sim_thread_sequential(void *ctx_ptr) {
   gpgpu_context *ctx = (gpgpu_context *)ctx_ptr;
diff --git a/src/stream_manager.cc b/src/stream_manager.cc
index b974791d..58c2ec4b 100644
--- a/src/stream_manager.cc
+++ b/src/stream_manager.cc
@@ -39,6 +39,10 @@ extern void SST_callback_memcpy_H2D_done();
 extern void SST_callback_memcpy_D2H_done();
 extern void SST_callback_memcpy_to_symbol_done();
 extern void SST_callback_memcpy_from_symbol_done();
+__attribute__((weak)) void SST_callback_memcpy_H2D_done() {}
+__attribute__((weak)) void SST_callback_memcpy_D2H_done() {}
+__attribute__((weak)) void SST_callback_memcpy_to_symbol_done() {}
+__attribute__((weak)) void SST_callback_memcpy_from_symbol_done() {}
 
 CUstream_st::CUstream_st() {
   m_pending = false;
```
Some of the above changes are inspired by or reference the [PR](https://github.com/accel-sim/gpgpu-sim_distribution/pull/81) by [WilliamMTK](https://github.com/William-An).

### Changes in accel-sim-framework:release:
```diff
diff --git a/gpu-simulator/.gitignore b/gpu-simulator/.gitignore
index 30b1ffd..aded91d 100644
--- a/gpu-simulator/.gitignore
+++ b/gpu-simulator/.gitignore
@@ -1,3 +1,3 @@
 bin/
 build/
-gpgpu-sim/
+# gpgpu-sim/
diff --git a/gpu-simulator/main.cc b/gpu-simulator/main.cc
index cbd42bd..71821b0 100644
--- a/gpu-simulator/main.cc
+++ b/gpu-simulator/main.cc
@@ -162,7 +162,7 @@ int main(int argc, const char **argv) {
         }
       }
       assert(k);
-      m_gpgpu_sim->print_stats();
+      m_gpgpu_sim->print_stats(m_gpgpu_sim->last_streamID);
     }
 
     if (sim_cycles) {
diff --git a/gpu-simulator/trace-driven/trace_driven.cc b/gpu-simulator/trace-driven/trace_driven.cc
index ff00351..b96473d 100644
--- a/gpu-simulator/trace-driven/trace_driven.cc
+++ b/gpu-simulator/trace-driven/trace_driven.cc
@@ -91,7 +91,8 @@ trace_kernel_info_t::trace_kernel_info_t(dim3 gridDim, dim3 blockDim,
                                          trace_parser *parser,
                                          class trace_config *config,
                                          kernel_trace_t *kernel_trace_info)
-    : kernel_info_t(gridDim, blockDim, m_function_info) {
+    : kernel_info_t(gridDim, blockDim, m_function_info,
+                    kernel_trace_info->cuda_stream_id) {
   m_parser = parser;
   m_tconfig = config;
   m_kernel_trace_info = kernel_trace_info;
```

**Comment by William-An** [comment]
GPGPU-Sim dev should be fixed now with accel-sim/gpgpu-sim_distribution#81 being merged.

**Comment by HomerG** [comment]
The issue persists even with the new merge. The changes reported by @ConvolutedDog are not reflected in the accel-sim-framework:release: version. I am still facing this issue following the instructions as stated while using the provided docker image.

**Comment by JRPan** [comment]
can you try dev? both accel-sim and gpgpu-sim. There will be a new release soon. 
Here, our regression tests pass. https://github.com/accel-sim/gpgpu-sim_distribution/actions/runs/13040205203/job/36380137221


Thanks.
