### ISSUE TITLE
wrong design for cache policy, LAZY_FETCH_ON_READ

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#48]
Hi,

I found that LAZY_FETCH_ON_READ policy (one of write-miss policies) is unacceptable policy (according to the simulation code).

Assume that write-miss occurs to cache line A.

LAZY_FETCH_ON_READ policy enables **WRITE request (tag X)** to write data into cache line A without fetching the cache line from the memory.

Here, if the **WRITE request (tag X)** does 4 B write request, the cache line A has to keep valid bit for each 4 B instead of each section (which might be unacceptable: require 128 / 4 bits for each cache line).

This is because, according to read miss policy (`rd_miss_base()`), if cache line A miss occurs by **READ request (tag Y)**, we need to write back cache line A (written by tag X).

However, the current `rd_miss_base()` does not generate partial WRITE BACK request for this 4 B (It just write back all Bytes in this sector).
In addition, current GPGPU-sim does not support partial DRAM write while modern DRAM supports this.

**Comment by mkhairy** [comment]
Hello, this error is fixed in the dev branch of our gpgpu-sim. We have pushed that recently, I think last week. If you pull, you should get this fix. The exact PR is listed below, and we merged that just last week.
https://github.com/accel-sim/gpgpu-sim_distribution/pull/14

We are going to officially release a new version of accel-sim and gpgpu-sim soon including this fix, but you can pull our dev branch for now to unblock you.

**Comment by allencho1222** [comment]
@mkhairy Thank you. I should have looked it carefully.

**Comment by allencho1222** [comment]
I still wonder whether the updated implementation is correct or not.

First of all, the implementation still does not consider the partially written sector.
As coded [here](https://github.com/accel-sim/gpgpu-sim_distribution/blob/6c9e13db93e4a1614f7401e9675c62ea40b65a3b/src/gpgpu-sim/l2cache.cc#L713), the function breakdowns request and set **all** byte mask within the sector if the sector mask is set.
(Without considering whether the sector is partially written or not (e.g., 4B out of 32B)).

In addition, if this partially written sector is written back to the memory, DRAM should support **read-modify-write** operation.
(, which is not implemented in GPGPU-sim)

**Comment by mkhairy** [comment]
@JRPan can you please take a look into this?

**Comment by mkhairy** [comment]
@allencho1222 if you know how to fix this? please go ahead and fix it, do PR and we will review and accept this? Thanks!

**Comment by JRPan** [comment]
Hi @allencho1222,
The L2 breakdown function you mentioned supports partially written byte mask. Please see line 730 [here](https://github.com/accel-sim/gpgpu-sim_distribution/pull/14/files#diff-26d079d67e442b12767b1ff901f79d3507466e0962ba13e527a88188e0c996caR730):
`mf->get_access_byte_mask() & mask`. 

`mf->get_access_byte_mask()` returns original partially written byte mask.
And then, the `mask` **AND** with the original byte mask. This unset other sectors and keep what was there within this sector.

**Comment by allencho1222** [comment]
Hi @JRPan,

Do we still need to modify the behavior of DRAM to support read-modify-write?

**Comment by mkhairy** [comment]
@allencho1222 can you explain in more detilas what do you mean by this?

**Comment by allencho1222** [comment]
@mkhairy 

To be specific, let's assume that a sector in the L2 cache line is partially written.

If a new cache line try to evict this dirty line, the dirty line must be written to the memory (GDDR or HBM).

However, because other bytes except dirty bytes are invalid (which are not accessed before the line is evicted),
the memory must read the whole sector first, write dirty bytes to the read sector, and write the sector to cells (This is the process called read-modify-write).

Am I missing something in the eviction policy of the cache?

**Comment by mkhairy** [comment]
@allencho1222  yeah, I think this is what we do in the commit I shared with you. When the sub-sector line is evicted, the dirty bytes along with the byte-dirty-mask is sent to the low-level memory (L1 -> L2 cache) and (L2 -> DRAM). We assume our DRAM/HBM supports sub-sector write, and we assume this complexity you described is already included in the DRAM write command. 
If you find something wrong with our code, let us know. or correct it by yourself and send us PR. Thanks!
